
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package calc;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int MINUS = 3;
  public static final int INT = 11;
  public static final int POW = 7;
  public static final int UMINUS = 10;
  public static final int DIV_INT = 6;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int DIV = 5;
  public static final int error = 1;
  public static final int RPAREN = 9;
  public static final int TIMES = 4;
  public static final int LPAREN = 8;
  public static final int FLOAT = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "DIV_INT",
  "POW",
  "LPAREN",
  "RPAREN",
  "UMINUS",
  "INT",
  "FLOAT"
  };
}

