
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package minijava;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int LBRACKET = 25;
  public static final int LPAREN = 23;
  public static final int SEMI = 27;
  public static final int INT = 10;
  public static final int PRINTLN = 20;
  public static final int LESS = 32;
  public static final int MINUS = 34;
  public static final int STATIC = 4;
  public static final int RPAREN = 24;
  public static final int NOT = 36;
  public static final int AND = 31;
  public static final int COMMA = 28;
  public static final int CLASS = 2;
  public static final int PLUS = 33;
  public static final int ASSIGN = 30;
  public static final int MAIN = 6;
  public static final int IF = 12;
  public static final int THIS = 17;
  public static final int DOT = 29;
  public static final int EOF = 0;
  public static final int BOOLEAN = 11;
  public static final int RETURN = 9;
  public static final int RBRACKET = 26;
  public static final int TRUE = 15;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int VOID = 5;
  public static final int TIMES = 35;
  public static final int LBRACE = 21;
  public static final int ELSE = 13;
  public static final int WHILE = 14;
  public static final int PUBLIC = 3;
  public static final int RBRACE = 22;
  public static final int EXTENDS = 8;
  public static final int STRING = 7;
  public static final int FALSE = 16;
  public static final int LENGTH = 19;
  public static final int IDENTIFIER = 38;
  public static final int INTEGER_LITERAL = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "PUBLIC",
  "STATIC",
  "VOID",
  "MAIN",
  "STRING",
  "EXTENDS",
  "RETURN",
  "INT",
  "BOOLEAN",
  "IF",
  "ELSE",
  "WHILE",
  "TRUE",
  "FALSE",
  "THIS",
  "NEW",
  "LENGTH",
  "PRINTLN",
  "LBRACE",
  "RBRACE",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "SEMI",
  "COMMA",
  "DOT",
  "ASSIGN",
  "AND",
  "LESS",
  "PLUS",
  "MINUS",
  "TIMES",
  "NOT",
  "INTEGER_LITERAL",
  "IDENTIFIER"
  };
}

